### ISSUE TITLE
Непонятно, в чём выводится время выполнения скрипта

### ISSUE THREAD

**Issue by AlphaBeth** [Drukhary/web-laba2#2]
8.88551E-4

1. Это секунды, минуты, часы, дни?
2. E-4 очень плохо воспринимается человеком

**Comment by Drukhary** [comment]
Поправил.
И теперь выглядит эта часть таблицы так
![image](https://user-images.githubusercontent.com/57765637/112754990-6afb3f00-8fe7-11eb-8076-cb37cf6d8705.png)
